### ISSUE TITLE
Question: only those scss files defined under styleUrls generates css?

### ISSUE THREAD

**Issue by ozexpert** [toddanglin/nativescript-dev-sass#32]
I have this component which uses styleUrls. However, in the folder, i have another scss file called `home.component.tns.scss` but seems when running nativescript, it generates the css files only if it is defined in the styleUrls. This component is shared between the web and the nativescript, so styleUrls is dynamically changed for nativescript (using: https://github.com/wwwalkerrun/nativescript-ngx-magic)
```
@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
  nsPath: './shared/pages/home/'
})
export class HomeComponent implements OnInit {
}
```
Is there a way to tell the nativescript-dev-sass to generate scss if *.scss is found under the folder?

**Comment by toddanglin** [comment]
That's an interesting problem. Do you have a small demo project project that can recreate the problem for local testing?

Based on the way the plugin is implemented, it should be converting all *.scss or *.sass files in your `app` directory. It simply uses the Node-Sass CLI and globs files with these extensions and converts. Are these style files in your `app` directory? If they are not, that could be the problem...

**Comment by ozexpert** [comment]
thanks for the reply. i just forked this project, so this would be a way to play around. 
https://github.com/wwwalkerrun/nativescript-ngx-magic

I don't need to run any special command to build css file, correct? I did `tns run ios`

**Comment by toddanglin** [comment]
Got it. I'm not super familiar with Nathan's "magic" repo.

@NathanWalker Does your template put shared styles outside of the working app directory? Curious how LiveSync handles that since I think it also only watches the `app` folder for changes.

@ozexpert You are correct. No special commands are required. The plugin creates a "hook" that automatically runs when the app is built or LiveSync'd. You should be able to try it by just putting a *.scss file somewhere in your `app` directory. I suspect the challenge here is that the shared styles are not in a directory normally watched by the plugin.

**Comment by ozexpert** [comment]
i'll play around more and try to figure out why. Thanks.

**Comment by ozexpert** [comment]
hmm.. nevermind. this is working as expected. closing.

**Comment by ozexpert** [comment]
looks like if i don't have any content inside scss, it's not likely to create a empty css file. I've tried adding a comment and seems working.

**Comment by toddanglin** [comment]
Ah! Yes. That is true. The SASS processor will not output an empty CSS file. Files that are prefixed with "_" (such as "_variables.scss") are also not converted to CSS files by default.

**Comment by wiedikerli** [comment]
When I start the android `tns run android` it wont recompile the `menu.component.tns.scss`.
When I delete the `.css` and run `tns build android` it generates the `.css` correctly. 

When the android is started and i change something in the `.scss` it does something in the console but it doesnt generate the `.css`.


### package.json
```
"nativescript-dev-sass": "^1.1.1"
```
### menu.component.ts
```
@Component({
    moduleId: module.id,
    selector: 'lac-menu',
    templateUrl: 'menu.html',
    styleUrls: ['menu.component.css']
})
```

![image](https://user-images.githubusercontent.com/2211563/27283849-8f4c5c48-54f6-11e7-9366-02f17303b476.png)

**Comment by toddanglin** [comment]
@ninjaonsafari Odd. I just tested this scenario in the demo app on Android and the SCSS compiling seems to be working as expected. I will add a new test case for a SCSS file with a similar name (`style test.component.tns.scss`) so you can try to reproduce locally.

Now, the demo project is not using Angular, but I wouldn't expect that to impact the way the SCSS processor works during a build or LiveSync.

Can you reproduce the problem using the demo project in your environment? Wonder if maybe there's a "competing" build step in your project monitoring SCSS files?

**Comment by wiedikerli** [comment]
@toddanglin I've downloaded the demo project and tested it successfully. Is there a way the add more loggin? so maybe I can see why it doesnt recompile.

In my project it works for app.android.scss 

But for the components styles i dont get this loggin message:

```
Transferring project files...
Successfully transferred home.component.tns.css.
Successfully transferred home.component.tns.css.
Refreshing application...
```

**Comment by toddanglin** [comment]
@ninjaonsafari You can locally modify the plugin to add as much logging as you'd like. Simply navigate to `node_modules > nativescript-dev-sass` and change the JavaScript OR, alternatively, clone this repo and modify the plugin TypeScript.

Either way, you should be able to experiment locally to see if you can uncover the source of the problem.

Meanwhile, if you can create a simple demo that DOES reproduce the problem, feel free to upload to GitHub and share the link to the repo. That might help me (and others) find the root cause from another direction.
